# database
spring.datasource.url=jdbc:h2:mem:timetracker;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# MyBatis
mybatis.type-aliases-package=timetracker.models

# spring
spring.main.allow-bean-definition-overriding=true